### ISSUE TITLE
Textarea doesn't have a scrollbar.

### ISSUE THREAD

**Issue by olivierlacan** [WDD-Social/wddsocial.com#10]
Bit of an issue, you need to select text to scroll down. Ideally this should adjust to the size of the article so there's no scrolling at all. But in the meantime, autoscroll would do.

![noscroll](http://f.cl.ly/items/2s2t211U2X1D3W3Z3514/Screen%20shot%202011-05-27%20at%2011.03.59%20PM.png)

**Comment by acolangelo** [comment]
We're planning on implementing autoexpanding text fields

**Comment by olivierlacan** [comment]
Can we work on auto-expanding pants for when I go to Outback too?
Thanks.
