### ISSUE TITLE
Placeholders look too much like actual content

### ISSUE THREAD

**Issue by olivierlacan** [WDD-Social/wddsocial.com#12]
I've come across this issue a lot, I always wonder whether the text in the placeholders is mine or not. The color differentiation is a bit too subtle and I think you might want to make it more obvious (italics, or prepending with "e.g.").

![placeholders](http://f.cl.ly/items/3N3p1Y1m1u1R0v0l1f3g/Screen%20shot%202011-05-27%20at%2011.09.23%20PM.png)

Furthermore, why add extra text fields to something like "Authors" when in most cases there will only be one author?
There's already a link to add another field, that should be enough. Although that link being an action verb "ADD", it should be button-like in my view. With a Noun Project "+" icon for instance.

**Comment by acolangelo** [comment]
A. Yes, I'm changing the text color. I was thinking that it was a little too close but wanted feeback, so thanks.

B. Too many buttons

**Comment by olivierlacan** [comment]
Then you should make those buttons look less obtrusive.
An action is a button, especially adding something to the UI.
