### ISSUE TITLE
Date/Time format on Account Edit

### ISSUE THREAD

**Issue by reactivepixel** [WDD-Social/wddsocial.com#4]
When updating account info you have to exactly match the yyyy-mm-dd format of the database. There is a affordance for graduation date, but not Birthday.

Solution notes:
stringtotime() solves all problems... Famine no longer exists, Wars are settled with water balloon fights, Puppies become unabandoned, and Orphans do not burn up in fires (they become flame proof). All thanks to stringtotime

**Comment by acolangelo** [comment]
Planning on implemented Date.js for easier formatting, and trust me, the formatting is not going to stay like that. Just for now before we get into heavy JS

**Comment by reactivepixel** [comment]
Solid, Just makin certain it was on your radar. It's those small touches that make / break the UX
