### ISSUE TITLE
Short description truncated

### ISSUE THREAD

**Issue by olivierlacan** [WDD-Social/wddsocial.com#9]
I did notice the character limit but the counter didn't update as I was typing and the textarea didn't prevent me from going over the limit. I'm assuming this is a minor feature you guys have yet to finish. 

![truncated](http://f.cl.ly/items/3x3w3U0i3K133H3x2a2x/Screen%20shot%202011-05-27%20at%2010.18.50%20PM.png)

**Comment by acolangelo** [comment]
Yep, that type of stuff is coming in the next few days
